# Generated by Django 5.2.1 on 2025-05-24 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0008_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmodel',
            name='completion_report',
        ),
        migrations.RemoveField(
            model_name='taskmodel',
            name='task_status',
        ),
        migrations.RemoveField(
            model_name='taskmodel',
            name='worked_hours',
        ),
        migrations.CreateModel(
            name='UserTaskResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=50)),
                ('completion_report', models.TextField(blank=True, null=True)),
                ('worked_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_accounts.taskmodel')),
            ],
        ),
    ]
