# Generated by Django 5.2.1 on 2025-05-25 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0009_remove_taskmodel_completion_report_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='task_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
